[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://www.factoresearch.com/*"
  to = "https://factoresearch.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://factoresearch.netlify.app/*"
  to = "https://factoresearch.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
